site_name: Nuclei - Community Powered Vulnerability Scanner
site_description: Learn how to use Nuclei engine to write your own custom security checks with very simple and easy to use templating syntax.
site_url: https://nuclei.projectdiscovery.io
repo_url: https://github.com/projectdiscovery/nuclei/
copyright: Copyright &copy; 2021 ProjectDiscovery, Inc.

# Configuration
theme:
  features:
    - tabs
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: false

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Nunito Sans
    code: Roboto Mono
  favicon: static/favicon.png
  icon:
    logo: logo

  logo: static/logo.png

# Plugins
plugins:
  - search

# Google Analytics

google_analytics:
  - UA-165996103-1
  - auto

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/projectdiscovery/nuclei
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pdnuclei

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home:
      - index.md

  - Getting Started:
      - Index: nuclei/get-started.md
      - Features: nuclei/get-started/#nuclei-features
      - Contribution: nuclei/get-started/#code-contribution
      - License: nuclei/get-started/#license

  - Templating Guide:
      - Introduction: templating-guide/index.md
      - Template Details: templating-guide/#template-details
      - HTTP: 
          - Base requests: templating-guide/protocols/http.md
          - Raw requests: templating-guide/protocols/http#raw-http-requests
          - HTTP fuzzing: templating-guide/protocols/http#http-fuzzing
          - Unsafe HTTP requests: templating-guide/protocols/http#unsafe-http-requests
          - Advance Fuzzing: templating-guide/protocols/http#advance-fuzzing
      - Headless: templating-guide/protocols/headless.md
      - Network: templating-guide/protocols/network.md
      - DNS: templating-guide/protocols/dns.md
      - File: templating-guide/protocols/file.md
      - Operators:
          - Matchers: templating-guide/operators/matchers.md
          - Extractors: templating-guide/operators/extractors.md
      - OOB Testing: templating-guide/interactsh.md
      - Helper Functions: templating-guide/helper-functions.md
      - Preprocessors: templating-guide/preprocessors.md
      - Workflows: templating-guide/workflows.md

  - Template Examples:
      - HTTP:
          - Base HTTP: template-examples/http.md
          - Raw HTTP: template-examples/http-raw.md
          - Unsafe HTTP: template-examples/http-smuggling.md
          - HTTP Payloads: template-examples/http-fuzzing.md
          - Race Condition: template-examples/http-race-conditions.md

      - DNS: template-examples/dns.md
      - File: template-examples/file.md
      - Headless: template-examples/headless.md
      - Network: template-examples/network.md
      - Workflow: template-examples/workflow.md

  - Releases:
      - Nuclei: releases/nuclei-changelog.md
      - Templates: releases/templates-changelog.md

  - FAQ:
      - Nuclei FAQ: faq/nuclei.md
      - Templates FAQ: faq/templates.md

